# Generated by Django 5.1.1 on 2024-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.CharField(max_length=100, unique=True)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField()),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MainImageURL', models.URLField()),
                ('AllImagesURLs', models.JSONField()),
                ('CategoryID', models.IntegerField()),
                ('CategoryName', models.CharField(max_length=100)),
                ('ItemSpecifications', models.JSONField()),
                ('EndTime', models.DateTimeField()),
                ('current_BID', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('BidHistory', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
