# Generated by Django 5.1.1 on 2024-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidapp', '0002_products_delete_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='BidHistory',
            field=models.JSONField(default=None),
        ),
    ]
