# Generated by Django 5.1.1 on 2024-09-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidapp', '0003_alter_products_bidhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='MainCategoryName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
