# Generated by Django 5.1.1 on 2024-09-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidapp', '0004_products_maincategoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ProductId', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='current_BIDDER',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
