# Generated by Django 5.1.1 on 2024-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidapp', '0005_userproducts_products_current_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current_BIDDER',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
