# Generated by Django 5.1.1 on 2024-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidapp', '0006_alter_products_current_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='ProductId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
